version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: teddy_db
      POSTGRES_USER: teddy_user
      POSTGRES_PASSWORD: teddy_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nestjs_backend
    restart: always
    depends_on:
      - database
      - otel-collector
      - prometheus
      - loki
      - rabbitmq
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: teddy_user
      DB_PASSWORD: teddy_password
      DB_NAME: teddy_db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      RABBITMQ_URL: amqp://rabbitmq:5672
    ports:
      - "3000:3000"
    command: npm run start:dev

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"  # Painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    ports:
      - "4318:4318"
      - "4317:4317"
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    command: ["--config=/etc/otel-config.yml"]

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  pg_data:
  grafana-data:
