version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: teddy_db
      POSTGRES_USER: teddy_user
      POSTGRES_PASSWORD: teddy_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nestjs_backend
    restart: always
    depends_on:
      - database
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: teddy_user
      DB_PASSWORD: teddy_password
      DB_NAME: teddy_db
    ports:
      - "3000:3000"
    command: npm run start:dev

volumes:
  pg_data:
