FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN yarn install --production

COPY . .

COPY .env.production .env

RUN yarn build

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "start"]
