global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
